#!/usr/bin/env bash

set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
frontend_root="$repo_root/frontend"

count_lines() {
	local path="$1"
	shift
	local files
	files="$(find "$path" -type f \( -name '*.ts' -o -name '*.tsx' \) "$@" -print 2>/dev/null)"

	if [ -z "$files" ]; then
		printf '0'
		return
	fi

	printf '%s\n' "$files" | xargs wc -l | tail -1 | awk '{ print $1 }'
}

count_test_files() {
	local path="$1"
	find "$path" -type f \( -name '*.test.ts' -o -name '*.test.tsx' \) -print 2>/dev/null | wc -l | tr -d ' '
}

count_go_lines() {
	local path="$1"
	find "$path" -type f -name '*.go' ! -name '*_test.go' -print0 2>/dev/null |
		xargs -0 -r wc -l | tail -1 | awk '{ print $1 }'
}

count_go_test_files() {
	local path="$1"
	find "$path" -type f -name '*_test.go' -print 2>/dev/null | wc -l | tr -d ' '
}

print_metric() {
	printf '| %s | %s | %s |\n' "$1" "$2" "$3"
}

cd "$repo_root"

legacy_uplot_lines="$(count_lines "$frontend_root/src/components/Uplot")"
legacy_uplot_lines=$((legacy_uplot_lines + $(count_lines "$frontend_root/src/lib/uPlotLib" ! -path '*/tests/*' ! -path '*/__mocks__/*')))
uplot_v2_lines="$(count_lines "$frontend_root/src/lib/uPlotV2" ! -path '*/__tests__/*')"
trace_lines="$(count_lines "$frontend_root/src/pages/TraceDetail")"
trace_lines=$((trace_lines + $(count_lines "$frontend_root/src/container/TraceWaterfall" ! -path '*/__tests__/*')))
trace_lines=$((trace_lines + $(count_lines "$frontend_root/src/container/PaginatedTraceFlamegraph" ! -path '*/__tests__/*')))
trace_lines=$((trace_lines + $(count_lines "$frontend_root/src/container/SpanDetailsDrawer" ! -path '*/__tests__/*')))

printf '%s\n' '# Refactoring Baseline'
printf '%s\n' ''
printf '%s\n' 'This report is generated by `yarn refactor:baseline`. It is a deletion gate, not a code-quality score: every refactoring change must delete code, remove a proven deletion blocker, or add safety coverage for a planned deletion.'
printf '%s\n' ''
printf '%s\n' "- Branch: \`$(git branch --show-current)\`"
printf '%s\n' ''
printf '%s\n' '## Scope'
printf '%s\n' ''
printf '%s\n' '| Module | Production TypeScript LOC | Direct test files |'
printf '%s\n' '| --- | ---: | ---: |'

print_metric 'Legacy uPlot (`components/Uplot`, `lib/uPlotLib`)' "$legacy_uplot_lines" "$(( $(count_test_files "$frontend_root/src/components/Uplot") + $(count_test_files "$frontend_root/src/lib/uPlotLib") ))"
print_metric 'uPlot V2 (`lib/uPlotV2`)' "$uplot_v2_lines" "$(count_test_files "$frontend_root/src/lib/uPlotV2")"
print_metric 'Trace detail presentation' "$trace_lines" "$(count_test_files "$frontend_root/src/pages/TraceDetail")"
print_metric 'Query stores (`retention`, `metrics explorer`, `rule state history`)' "$(count_go_lines "$repo_root/pkg/query-service/app/retentionstore") / $(count_go_lines "$repo_root/pkg/query-service/app/metricsexplorerstore") / $(count_go_lines "$repo_root/pkg/query-service/app/rulestatehistorystore")" "$(count_go_test_files "$repo_root/pkg/query-service/app/retentionstore") / $(count_go_test_files "$repo_root/pkg/query-service/app/metricsexplorerstore") / $(count_go_test_files "$repo_root/pkg/query-service/app/rulestatehistorystore")"

cat <<'EOF'

## Reachable Trace Entry

`AppRoutes/routes.ts` registers `TraceDetail`; `AppRoutes/pageComponents.ts` loads `pages/TraceDetail/index`. The page renders `TraceWaterfall` and `PaginatedTraceFlamegraph`, so those modules are not deletion candidates.

## Legacy uPlot Consumers

EOF

legacy_consumers="$(rg -l "from ['\"](components/Uplot|lib/uPlotLib)" "$frontend_root/src" \
	--glob '*.{ts,tsx}' \
	--glob '!**/*.test.*' \
	--glob '!**/__tests__/**' \
	--glob '!**/tests/**' \
	--glob '!**/__mocks__/**' \
	| sed "s#^$repo_root/##" \
	| sort || true)"

if [ -z "$legacy_consumers" ]; then
	printf '%s\n' 'No production imports remain. The legacy uPlot implementation has been deleted.'
else
	printf '%s\n\n' 'These production imports are the remaining migration queue:'
	printf '%s\n' "$legacy_consumers" | sed 's#^#- `#; s#$#`#'
fi

cat <<'EOF'

## Deletion Rules

1. A candidate needs no route, dynamic import, production import, or generated-code reference.
2. Shared code is extracted only when it is consumed by the retained implementation.
3. A deletion must run the affected unit tests, frontend build, and the applicable ClickHouse/SQLite API check before merging.
EOF
