name: commitci

on:
  pull_request:
    branches:
      - main
  merge_group:
    types:
      - checks_requested

jobs:
  refcheck:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: check
        run: |
          if grep -R --include="*.go" '.*/ee/.*' pkg/; then
            echo "Error: Found references to 'ee' packages in 'pkg' directory"
            exit 1
          else
            echo "No references to 'ee' packages found in 'pkg' directory"
          fi

          if grep -R --include="*.go" '.*/ee/.*' cmd/community/; then
            echo "Error: Found references to 'ee' packages in 'cmd/community' directory"
            exit 1
          else
            echo "No references to 'ee' packages found in 'cmd/community' directory"
          fi
