name: goci

on:
  pull_request:
    branches:
      - main
  merge_group:
    types:
      - checks_requested

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: self-checkout
        uses: actions/checkout@v4
      - name: go-install
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.12"
      - name: go-test
        run: go test -race ./...

  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: self-checkout
        uses: actions/checkout@v4
      - name: go-install
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.12"
      - name: go-fmt
        run: |
          out=$(gofmt -l -s .)
          if [ -n "$out" ]; then
            echo "The following files are not formatted with gofmt -s:"
            echo "$out"
            exit 1
          fi

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: self-checkout
        uses: actions/checkout@v4
      - name: go-install
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.12"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.12.2
          args: --timeout 10m

  deps:
    runs-on: ubuntu-latest
    steps:
      - name: self-checkout
        uses: actions/checkout@v4
      - name: go-install
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.12"
      - name: go-deps
        run: |
          go mod tidy
          git diff --compact-summary --exit-code || (echo; echo "Unexpected difference in go.mod/go.sum. Run 'go mod tidy' locally and commit."; exit 1)

  build:
    runs-on: ubuntu-latest
    steps:
      - name: self-checkout
        uses: actions/checkout@v4
      - name: go-install
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.12"
      - name: qemu-install
        uses: docker/setup-qemu-action@v3
      - name: aarch64-install
        run: |
          set -ex
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu musl-tools
      - name: node-install
        uses: actions/setup-node@v5
        with:
          node-version: "22"
      - name: docker-community
        shell: bash
        run: |
          make docker-build-community
  openapi:
    runs-on: ubuntu-latest
    steps:
      - name: self-checkout
        uses: actions/checkout@v4
      - name: go-install
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.12"
      - name: generate-openapi
        run: |
          go run cmd/community/*.go generate openapi
          git diff --compact-summary --exit-code || (echo; echo "Unexpected difference in openapi spec. Run go run cmd/community/*.go generate openapi locally and commit."; exit 1)
