name: jsci

on:
  pull_request:
    branches:
      - main
  merge_group:
    types:
      - checks_requested

jobs:
  tsc:
    runs-on: ubuntu-latest
    steps:
      - name: self-checkout
        uses: actions/checkout@v4
      - name: node-install
        uses: actions/setup-node@v5
        with:
          node-version: "22"
      - name: install-frontend
        run: cd frontend && yarn install
      - name: tsc
        run: cd frontend && yarn tsc --noEmit

  test:
    runs-on: ubuntu-latest
    steps:
      - name: self-checkout
        uses: actions/checkout@v4
      - name: node-install
        uses: actions/setup-node@v5
        with:
          node-version: "22"
      - name: install-frontend
        run: cd frontend && yarn install
      - name: js-test
        run: cd frontend && yarn test

  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: self-checkout
        uses: actions/checkout@v4
      - name: node-install
        uses: actions/setup-node@v5
        with:
          node-version: "22"
      - name: install-frontend
        run: cd frontend && yarn install
      - name: js-fmt
        run: cd frontend && yarn fmt

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: self-checkout
        uses: actions/checkout@v4
      - name: node-install
        uses: actions/setup-node@v5
        with:
          node-version: "22"
      - name: install-frontend
        run: cd frontend && yarn install
      - name: js-lint
        run: cd frontend && yarn lint

  languages:
    runs-on: ubuntu-latest
    steps:
      - name: self-checkout
        uses: actions/checkout@v4
      - name: run
        run: bash frontend/scripts/validate-md-languages.sh

  openapi:
    runs-on: ubuntu-latest
    steps:
      - name: self-checkout
        uses: actions/checkout@v4
      - name: node-install
        uses: actions/setup-node@v5
        with:
          node-version: "22"
      - name: install-frontend
        run: cd frontend && yarn install
      - name: generate-api-clients
        run: |
          cd frontend && yarn generate:api
          git diff --compact-summary --exit-code || (echo; echo "Unexpected difference in generated api clients. Run yarn generate:api in frontend/ locally and commit."; exit 1)
